### ISSUE TITLE
puma in fluentd-ui won't start because of hosts file entry

### ISSUE THREAD

**Issue by prein** [minimum2scp/dockerfiles#304]
Hi,
Puma in fluentd-ui (pulled today from docker hub) image refuses to start with:  `Cannot assign requested address - bind(2) for "::1" port 9292 (Errno::EADDRNOTAVAIL)`
This seems to be caused by https://github.com/puma/puma/issues/1022 and can be temporarily workarounded by removing "localhost" name for "::1" entry in /etc/hosts in the running docker container.

**Comment by minimum2scp** [comment]
Thanks for your report. I'll fix it.

**Comment by minimum2scp** [comment]
@prein 
I fixed this issue by #305, and new image is built and pushed.
Please try new image.

**Comment by prein** [comment]
@minimum2scp 
Thanks! I've just tried and confirmed that it works.
